version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: CW_mysql
    volumes:
     - ./mysql/data:/var/lib/mysql
     - ./mysql/scripts:/docker-entrypoint-initdb.d
    ports:
      - 3310:3306
    env_file:
      - ./mysql/.env
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: CW_phpmyadmin
    env_file:
      - ./phpmyadmin/.env
    ports:
      - 8090:80
    depends_on:
      - mysql

  python3_http:
    container_name: CW_Python3_HTTP
    build: python3/http
    volumes:
      - ./python3/http:/app
    working_dir: /app
    command: python3 app.py
    depends_on:
      - mysql
  
  python3_ping3:
    container_name: CW_Python3_ping3
    build: python3/ping3
    volumes:
      - ./python3/ping3:/app
    working_dir: /app
    command: python3 app.py
    depends_on:
      - mysql

  python3_socket:
    container_name: CW_Python3_socket
    build: python3/socket
    volumes:
      - ./python3/socket:/app
    working_dir: /app
    command: python3 app.py
    depends_on:
      - mysql